### ISSUE TITLE
Publish wheel to PyPI

### ISSUE THREAD

**Issue by hickford** [kmike/datrie#21]
Consider publishing a wheel to PyPI. Makes installation more reliable (in particular possible on Windows and OS X without a compiler). See also http://pythonwheels.com/

https://pypi.python.org/pypi/datrie

**Comment by superbobry** [comment]
Hello, @hickford can you please try any of the wheels [here](https://ci.appveyor.com/project/superbobry/datrie) and let me know if it works for you. 

To download the wheel pick your arch. and Python version,
![screenshot 2015-05-02 20 30 23](https://cloud.githubusercontent.com/assets/185856/7442045/1f0d96e2-f10a-11e4-9ee8-c11c53204f5b.png)

then the go to the Artifacts tab.
![screenshot 2015-05-02 20 30 37](https://cloud.githubusercontent.com/assets/185856/7442044/1f0879a0-f10a-11e4-9bd7-d696d1f90b54.png)

**Comment by hickford** [comment]
Hi Sergei. That Appveyor site crashed my browser, but the wheel worked a treat (Windows 64 bit Python). Nice work.

    pip install https://ci.appveyor.com/api/buildjobs/x8biwvd1m0toevik/artifacts/dist/datrie-0.7-cp34-none-win_amd64.whl

**Comment by superbobry** [comment]
Glad it worked :)

The next PyPI release will have wheels.

**Comment by hickford** [comment]
Hi. Any progress?

**Comment by kmike** [comment]
@superbobry ouch, I realised you don't have pypi upload powers - could you please tell me your pypi username, so that I can add you?

**Comment by superbobry** [comment]
Hah, I never realised this either, but I was planning to upload `datrie` today, so that's perfectly timed :)

My username is `Sergei.Lebedev`.

**Comment by kmike** [comment]
@superbobry done! (for datrie and marisa-trie)

**Comment by superbobry** [comment]
Thanks!

**Comment by superbobry** [comment]
Wheels for both OS X and Windows are now on PyPI.

**Comment by hickford** [comment]
Thanks both
