### ISSUE TITLE
RecordTries

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [kmike/datrie#23]
for more efficient storage of values/tuples that don't need pickle

**Comment by superbobry** [comment]
Hello Ronny, can you please elaborate a bit on the use-cases you have in mind? 

The only place where we seem to use `pickle` is I/O. In theory we can improve space consumption by introducing a typed `Trie` which delegates to [`struct`](https://docs.python.org/2/library/struct.html) for serialization.

**Comment by superbobry** [comment]
To be addressed as part of #31.
