### ISSUE TITLE
0.8

### ISSUE THREAD

**Issue by dallbee** [kmike/datrie#27]
Any chance we can get version 0.8 pushed out? There's been significant updates since 2004 (I'm looking at you, https://github.com/kmike/datrie/commit/4bb5493ce269cc0773afc15a1a3ee2a677c32757). 

Appreciate you guys working on this. It's by far the best write-enabled trie implementation.

**Comment by superbobry** [comment]
Hi, I think it makes sense to release 0.8 after #25 and unfortunately I didn't have the time to work on it yet.

**Comment by superbobry** [comment]
I've released 0.7.1, will focus on #25 in the following release.

**Comment by dallbee** [comment]
Thank you!
