### ISSUE TITLE
More simple dict methods

### ISSUE THREAD

**Issue by kmike** [kmike/datrie#3]
* get
* pop
* update

* fromkeys - should it infer the alphabet?

**Comment by superbobry** [comment]
It seems that `datrie` has the same weird iteration bug as `marisa_trie`, because it doesn't explicitly implement `__iter__`.

See discussion in [marisa_trie#16](https://github.com/kmike/marisa-trie/issues/16) for details.

**Comment by superbobry** [comment]
`fromkeys` is not part of the `*Mapping` API according to the [docs](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes).
