### ISSUE TITLE
Possible bug with range initialization

### ISSUE THREAD

**Issue by superbobry** [kmike/datrie#30]
Reported in this [SO](http://stackoverflow.com/questions/37041762/python-datrie-chinese-unicode-string-insert-error) question:

```python
>>> import datrie
>>> trie = datrie.Trie(ranges=[(u'\u0000', u'\u9FFF')])
>>> trie["颖礼仿古烟盒折扣"] = 42
>>> "颖礼仿古烟盒折扣" in trie
False
>>> trie.keys()
['\x96<']
```

The characters in a string are within the specified range:

```python
>>> ord('\u9FFF')
40959
>>> list(map(ord, "颖礼仿古烟盒折扣"))
[39062, 31036, 20223, 21476, 28895, 30418, 25240, 25187]
```

Overflow bug somewhere?

**Comment by tanghuang** [comment]
thanks to superbobry. I am the one report the  question.  we haven't fix it  till now.

**Comment by superbobry** [comment]
Appologies, I haven't had a chance to look into this, but I will at some point.

**Comment by superbobry** [comment]
The answer is in #10: `datrie` the library doesn't support alphabet ranges of size larger than 256.

**Comment by yao62995** [comment]
You can solve it as follows:

    >>> import datrie
    >>> trie = datrie.Trie(ranges=[(u'\x00', u'\xff')])
    >>> key="颖礼仿古烟盒折扣"
    >>> trie[key.decode('latin1')]=42
    >>> trie[key.decode('latin1')]
    42
    >>> trie.keys()
    [u'\xe9\xa2\x96\xe7\xa4\xbc\xe4\xbb\xbf\xe5\x8f\xa4\xe7\x83\x9f\xe7\x9b\x92\xe6\x8a\x98\xe6\x89\xa3']
