### ISSUE TITLE
pickling support

### ISSUE THREAD

**Issue by kmike** [kmike/datrie#4]
See https://github.com/kmike/datrie/wiki/pickling-support for possible hacks. 
Another option is to implement this properly, in Cython wrapper.

**Comment by superbobry** [comment]
Current state of pickling:

```
>>> import pickle
>>> import datrie
>>> t = datrie.Trie("acgt")
>>> pickle.loads(pickle.dumps(t))
<datrie.Trie object at 0x1022d01c8>
>>> len(pickle.loads(pickle.dumps(t)))
[1]    12678 segmentation fault  python
```

That is: we **can** pickle and unpickle the thing, but results are unsatisfying :)

**Comment by kmike** [comment]
:+1:
